name: Create Issue on Push

on:
  push:
    branches: [ main ]

jobs:
  create-issue-automatically:
    runs-on: ubuntu-latest

    permissions:
        issues: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create Issue
      id: create-issue
      run: |
        curl --request POST \
        --url https://api.github.com/repos/${{ github.repository }}/issues \
        --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
        --header 'content-type: application/json' \
        --data '{
           "title": "Automated issue for commit: ${{ github.sha }}",
           "body": "This issue was automatically created by the GitHub Action workflow **${{ github.workflow }}**. \n\n The commit hash was: _${{ github.sha }}_.",
           "labels": ["failed-test-case"]
        }' \
        --fail

      # run: |
      #   echo "Push event detected. Creating an issue..."
      #   body="Push event detected by GitHub Actions."
      #   title="Push Event on Branch: ${{ github.ref }}"
      #   echo "Title: $title"

        
      #   # issue_url=$(curl --request POST \
      #   #   --url https://api.github.com/repos/${{ github.repository }}/issues \
      #   #   --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
      #   #   --header 'content-type: application/json' \
      #   #   --data '{
      #   #     "title": "'"$title"'",
      #   #     "body": "This issue was automatically created by the GitHub Action workflow **${{ github.workflow }}**. \n\n The commit hash was: _${{ github.sha }}_."
      #   #   }' \
      #   #   --fail

      #   issue_url=$(curl -X POST \
      #     -H "Accept: application/vnd.github.v3+json" \
      #     -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
      #     -d '{
      #       "title": "'"$title"'",
      #       "body": "'"$body"'"
      #     }' \
      #     "https://api.github.com/repos/${{ github.repository }}/issues" | jq -r '.html_url')

      #   # echo "Issue created: $issue_url"  

      #   echo "Issue created: $issue_url"

      # run: |
      #     curl --request POST \
      #     --url https://api.github.com/repos/${{ github.repository }}/issues \
      #     --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
      #     --header 'content-type: application/json' \
      #     --data '{
      #       "title": "Automated issue for commit: ${{ github.sha }}",
      #       "body": "This issue was automatically created by the GitHub Action workflow **${{ github.workflow }}**. \n\n The commit hash was: _${{ github.sha }}_."
      #       }' \
      #     --fail

      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # call-workflow:
  #   uses: prhsag/alpha/.github/workflows/reusable-issue-workflow.yml@main

