name: Create Issue on Push

on:
  push:
    branches:
      - main

jobs:
  create-issue:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create Issue
      id: create-issue
      run: |
        echo "Push event detected. Creating an issue..."
        body="Push event detected by GitHub Actions."
        title="Push Event on Branch: ${{ github.ref }}"

        # Use the GitHub API to create an issue
        issue_url=$(curl -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -d '{
            "title": "'"$title"'",
            "body": "'"$body"'"
          }' \
          "https://api.github.com/repos/${{ github.repository }}/issues" | jq -r '.html_url')

        echo "Issue created: $issue_url"
        
        # You can add more logic here if needed.

      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
