name: Bypass QM's Vault OIDC Login
on:
    workflow_dispatch: 


jobs:
    generate-jwt-token:
        name: Generate a Workflow JWT Token for authorization to Vault
        permissions:
            id-token: write
            contents: read
        runs-on: ubuntu-latest
        steps:
            - name: Generate OIDC Token
              id: generate-oidc-token  
              uses: SAG-Trial/QM/.github/actions/GenerateOIDCToken@main  
        outputs:
            oidc: ${{ steps.generate-oidc-token.outputs.OIDC_BASE64 }}
        
    reuse-conditional-vault:
      name: Bypassing QM Repo and calling Vault login directly
      needs: generate-jwt-token
      permissions:
          id-token: write
          contents: read
      uses: SAG-Trial/QM/.github/workflows/reusable-vault-login.yaml@main
      secrets: 
        PARENT_OIDC: ${{needs.generate-jwt-token.outputs.oidc}}
    