name: Call QM Repo which calls Private repo
on:
    workflow_dispatch: 



jobs:
    call-qm:
        name: Call QM
        uses: SAG-Trial/QM/.github/workflows/read-composite-action-internal-private.yaml@main
        secrets: inherit

        

    get-weather:
        runs-on: ubuntu-latest
        needs: call-qm
        steps:
            - name: Get Weather
              uses: SAG-Trial/QM/.github/actions/GetWeather@main
              env:
                WEATHER_API: ${{ needs.call-qm.outputs.weather_api_key }}
        
