name: Call QM Repo which calls Private repo
on:
    workflow_dispatch: 


jobs:
    call-qm:
        name: Call QM
        uses: SAG-Trial/QM/.github/workflows/read-composite-action-internal-private.yaml@main