name: Create iTrac Ticket Manually

on:
    workflow_dispatch: 

jobs:
    create-itrac-ticket:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: POST Request iTrac Ticket
          id: create-ticket
          run: |
            curl --request POST \
            --url 'https://itrac.eur.ad.sag/rest/api/2/issue' \
            --user 'sups@softwareag.com:${{secrets.ITRAC_TOKEN}}' \
            --header 'Accept: application/json' \
            --header 'Content-Type: application/json' \
            --data '{
                { "fields": { "project": { "key": "AIMT" }, "summary": "REST ye merry gentlemen.", "description": "Creating of an issue using project keys and issue type names using the REST API", "issuetype": { "name": "Bug" } } }
            }'

          env:
            ITRAC_TOKEN:  MTkyNzgzMDI2MTgxOiiSNv4rS88DmyDYX/70gi45AZvC