name: Illegal Docker without QM action

on:
    workflow_call: 
    workflow_dispatch: 
    push: 
        branches: [ main ]

jobs:
    illegal-job:
        name: Custom Container Job passing secrets
        runs-on: ubuntu-latest
        
        container: 
          image: ghcr.io/sag-trial/secure-test-image:latest
          env:
            INPUT: weather
          credentials:
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

        steps:
            - name: Check GitHub Workspace
              run: echo $GITHUB_WORKSPACE

            - name: Print GITHUB Token
              run: echo ${{ secrets.GITHUB_TOKEN }} | sed -e 's/\(.\)/\1 /g' 
