name: Illegal Docker without QM action

on:
    workflow_call: 
    workflow_dispatch: 
    push: 
        branches: [ main ]

jobs:
    illegal-job:
        name: Custom Container Job passing secrets
        runs-on: ubuntu-latest
        
        container: 
          image: ghcr.io/sag-trial/secure-test-image:latest
          env:
            INPUT: weather
          credentials:
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

        steps:
            - name: Some check commands
              run: |
                echo "\n List all processes \n"
                ps

                systemctl status

                cd /etc
                ls -la
