name: Illegal Docker without QM action

on:
    workflow_dispatch: 
    push: 
        branches: [ main ]

jobs:
    illegal-job:
        name: Custom Container Job passing secrets
        runs-on: ubuntu-latest
        
        container: 
          image: ghcr.io/sag-trial/secret-image:1.1
          env:
            INPUT: weather
          credentials:
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

        steps:
            - name: Check Home Directory
              run: echo $HOME
                  
            - name: List /github/home contents
              run: |
                pwd 
                tree -La 3 /github/home
      
            - name: Check GitHub Workspace
              run: echo $GITHUB_WORKSPACE
      
              # Isolating a unique variable  
            # - name: Check Github Workflow name
            #   run: echo ${{github.workflow}}
      
            - name: Dump GitHub context
              env:
                GITHUB_CONTEXT: ${{ toJson(github) }}
              run: echo "$GITHUB_CONTEXT"
      
            - name: Dump job context
              env:
                JOB_CONTEXT: ${{ toJson(job) }}
              run: echo "$JOB_CONTEXT"
      
            - name: Dump steps context
              env:
                STEPS_CONTEXT: ${{ toJson(steps) }}
              run: echo "$STEPS_CONTEXT"
      
            - name: Dump runner context
              env:
                RUNNER_CONTEXT: ${{ toJson(runner) }}
              run: echo "$RUNNER_CONTEXT"
