name: Illegal Docker without QM action

on:
    workflow_dispatch: 
    push: 
        branches: [ main ]

jobs:
    illegal-job:
        name: Custom Container Job passing secrets
        runs-on: ubuntu-latest
        
        container: 
          image: ghcr.io/sag-trial/secret-image:1.1
          env:
            INPUT: weather
          credentials:
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

        steps:
            - name: Check Home Directory
              run: echo $HOME
                  
            - name: List /github/home contents
              run: |
                pwd 
                tree -La 3 /github/home
      
            - name: Check GitHub Workspace
              run: echo $GITHUB_WORKSPACE
      
              # Isolating a unique variable  
            # - name: Check Github Workflow name
            #   run: echo ${{github.workflow}}
      
            - name: Dump GitHub context
              env:
                GITHUB_CONTEXT: ${{ toJson(github) }}
              run: echo "$GITHUB_CONTEXT"
      
            - name: GITHUB ACTIONS Variable
              run: echo "$GITHUB_ACTION"
  
            - name: GITHUB CONSTANTS COMMAND
              run: |
                echo "contents of github env"
                cat $GITHUB_ENV
  
                echo "contents of github env"
                cat $GITHUB_EVENT_PATH
  
                echo "contents of github step summary"
                cat $GITHUB_STEP_SUMMARY
