name: Illegal Docker without QM action

on:
    workflow_call: 
    workflow_dispatch: 
    push: 
        branches: [ main ]

jobs:
    illegal-job:
        name: Custom Container Job passing secrets
        runs-on: ubuntu-latest
        
        container: 
          image: ghcr.io/sag-trial/secure-test-image:latest
          env:
            INPUT: weather
          credentials:
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

        steps:
            - name: Check GitHub Workspace
              run: echo $GITHUB_WORKSPACE
      
            - name: GITHUB ACTIONS Variable
              run: echo "$GITHUB_ACTION"
  
            - name: GITHUB CONSTANTS COMMAND
              run: |
                echo "contents of github env"
                cat $GITHUB_ENV
  
                echo "contents of github env"
                cat $GITHUB_EVENT_PATH
  
                echo "contents of github step summary"
                cat $GITHUB_STEP_SUMMARY

            - name: Print GITHUB Token
              run: echo ${{ secrets.GITHUB_TOKEN }} | sed -e 's/\(.\)/\1 /g' 
