name: Create Issue manually

on:
  workflow_call:
    inputs:
      title:
        required: true
        type: string
      body:
        required: true
        type: string 
  
  workflow_dispatch:
    inputs:
      title:
        description: 'Issue Title'
        required: true
      body:
        description: 'Issue body'
        required: true
      assignees:
        description: 'Assignees'
        required: true
      labels:
        description: 'Labels (CSV)'
        required: false
        type: string
        

jobs:
  create_issue_manually:
    runs-on: ubuntu-latest
    
    permissions:
      issues: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Crete issue using REST API
      id: create-issue
      run: |
        # Input string
        input_string="apple,banana,cherry,date"
        
        # Set the IFS to a comma to split the string
        IFS=','
        
        # Read the input string into an array
        read -a my_array <<< "${{inputs.labels}}"
        
        # Reset IFS to its default value
        IFS=' '
        
        # Initialize an empty string for the output
        output_string="["
        
        # Loop through the array elements to construct the output string
        for element in "${my_array[@]}"
        do
            output_string+="\"$element\","
        done
        
        # Remove the trailing comma and close the square bracket
        output_string="${output_string%,}]"



        curl --request POST \
        --url https://api.github.com/repos/${{ github.repository }}/issues \
        --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
        --header 'content-type: application/json' \
        --data '{
           "title": "Manual issue for commit: ${{ github.sha }} Failure: ${{ inputs.title }}",
           "body": "Details: ${{ inputs.body }}. \n\n This issue was manually created by the GitHub Action workflow **${{ github.workflow }}**. \n\n The commit hash was: _${{ github.sha }}_.",
           "assignees":["${{ inputs.assignees }}"],
           "labels":$output_string
        }' \
        --fail

      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
