name: Read from a Secret Repo with SSH Key
on:
    workflow_dispatch: 

jobs:
  write-to-private:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # - name: Read file contents from private repo
      #   uses: SAG-Trial/consumer/.github/actions/GetPwdFile@main
      #   env:
      #       SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Check out main repository
        uses: actions/checkout@v3

      - name: Get composite run steps repository
        uses: actions/checkout@v3
        with:
            repository: SAG-Trial/SecretSubModule
            ref: main
            # token: ${{ secrets.REPO_PAT }}
            ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
            path: .github/actions

      - name: List contents of .github/actions
        run: ls -R .github/actions
        shell: bash  
        