name: Call Workflow to GET Request

on:
  workflow_dispatch:

jobs:
  call_b_workflow:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Trigger workflow_b using POST Request
      id: trigger-workflow-b
      run: |
        curl --location 'https://api.github.com/repos/SAG-Trial/b/actions/workflows/get-weather.yml/dispatches' \
        --header 'Accept: application/vnd.github+json' \
        --header 'Content-Type: application/json' \
        --header 'Authorization: Bearer ${{ secrets.REPO_A_TOKEN }}' \
        --data '{
            "ref":"main"
        }'
      env:
        ORG_TOKEN: ${{ secrets.ORG_TOKEN }}
    
