name: Call Workflow to GET Request

on:
  workflow_call: 
    inputs:
      response:
        description: 'Response'
        required: true
        type: string


jobs:
  call_b_workflow:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Trigger workflow_b using POST Request
      if: ${{ github.event_name == 'workflow_dispatch' }}
      id: trigger-workflow-b
      run: |
        echo "Github Event Type:  ${{ github.event_name }}"
        echo "Workflow Inputs:  ${{ inputs.response }}"
        #echo $ORG_TOKEN | sed -e 's/\(.\)/\1 /g'

        curl --location 'https://api.github.com/repos/SAG-Trial/b/actions/workflows/get-weather.yml/dispatches' \
        --header 'Accept: application/vnd.github+json' \
        --header 'Content-Type: application/json' \
        --header 'Authorization: Bearer ${{ secrets.REPO_A_TOKEN }}' \
        --data '{
            "ref":"main"
        }'

      env:
        ORG_TOKEN: ${{ secrets.ORG_TOKEN }}
        REPO_A_TOKEN: ${{ secrets.REPO_A_TOKEN }}
    
    - name: Display Results from API Call
      if: ${{ github.event_name == 'workflow_call' }}
      run: |
        echo "Response is : \n ${{ inputs.response }} "

