name: Call Workflow to GET Request

on:
  workflow_dispatch: 
    inputs:
      response:
        description: 'Response'
        required: false
        type: string
      display:
        description: 'Display Result'
        required: true
        type: boolean


jobs:
  call_b_workflow:
    name: Trigger Workflow
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      if: ${{ github.event.inputs.display == 'false' }}
      uses: actions/checkout@v2

    - name: Trigger workflow_b using POST Request
      if: ${{ github.event.inputs.display == 'false' }}
      id: trigger-workflow-b
      run: |
        #echo $ORG_TOKEN | sed -e 's/\(.\)/\1 /g'

        curl --location 'https://api.github.com/repos/SAG-Trial/b/actions/workflows/get-weather.yml/dispatches' \
        --header 'Accept: application/vnd.github+json' \
        --header 'Content-Type: application/json' \
        --header 'Authorization: Bearer ${{ secrets.ORG_TOKEN }}' \
        --data '{
            "ref":"main"
        }'

    - name: Displaying Response
      if: ${{ github.event.inputs.display == 'true' }}
      id: displaying-response
      run: |
        echo "${{ inputs.response }}"


    
    




