name: Write to a Secret Repo with SSH Key
on:
    workflow_dispatch: 

jobs:
  write-to-private:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Read file contents from private repo
        uses: ./.github/actions/GetPwdFile@main
        env:
            SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        